# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://rmukhamet.ru"
title = "Rafael Mukhametdzhanov"
enableRobotsTXT = true
enableEmoji = true
theme = "minimal"

paginate = 3              # Number of articles displayed on the homepage  
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-35259440-2"      # UA-XXXXXXXX-X
defaultContentLanguage = "ru"           # Default language to use


[params]
  since = "2020"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary
  author = "Rafael Mukhametdzhanov"
  description = "no content"
  copyright = " "  
  githubUsername = "rmukhamet"
  accent = "magenta"
  showBorder = true
  backgroundColor = "white"
  font = "Raleway" # should match the name on Google Fonts!
  highlight = true 
  highlightStyle = "default"
  highlightLanguages = ["go", "typescript", "kotlin"]
  Subtitle = "Hugo is Absurdly Fast!"

    
  # site info (optional)                                  
  #logoTitle = "Rafael"        # default: the title value    
  #keywords = ["Homepage", "CV", "Resume", "golang", "developer"]

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"


[sitemap]                 # essential                    
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[languages.en]
  languageCode = "en"

[languages.ru]
  languageCode = "ru"

[[languages.ru.menu.main]]                   
  name = "Главная"
  weight = 1
  identifier = "home"
  url = "/"

[[languages.ru.menu.main]]                   
    url = "https://github.com/rmukhamet/cv/releases/latest/download/CV_Rafael_Mukhametdzhanov.pdf"
    name = "CV"
    weight = 200

[[languages.ru.menu.main]]                   
  name = "Теги"
  weight = 90
  identifier = "tags"
  url = "/tags/"

[[languages.ru.menu.main]]                   
  name = "Категории"
  weight = 100
  identifier = "categories"
  url = "/categories/"

[[languages.en.menu.main]]
 name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[languages.en.menu.main]]                   
    url = "https://github.com/rmukhamet/cv/releases/latest/download/cv_tex.pdf"
    name = "CV"
    weight = 200

[[languages.en.menu.main]]                   
  name = "Tags"
  weight = 90
  identifier = "tags"
  url = "/tags/"

[[languages.en.menu.main]]                   
  name = "Categories"
  weight = 100
  identifier = "categories"
  url = "/categories/"



[[languages.ru.menu.icon]]
  url =  "https://twitter.com/RMukhamet"
  name = "twitter"
  weight = 1

[[languages.ru.menu.icon]]
  url = "https://github.com/rmukhamet"
  name = "github"
  weight = 2

[[languages.ru.menu.icon]]
  url = "https://www.instagram.com/rafaelfyaritovich/"
  name = "instagram"
  weight = 3

[[languages.ru.menu.icon]]
  url = "https://www.facebook.com/rmukhametdzhanov"
  name = "facebook"
  weight = 4

[[languages.ru.menu.icon]]
  url = "https://www.strava.com/athletes/rmukhamet"
  name = "strava"
  weight = 5

[[languages.ru.menu.icon]]
  url = "https://www.linkedin.com/in/rafaelmoukhametdjanov/"
  name = "linkedin"
  weight = 6

[[languages.ru.menu.icon]]
  url = "https://t.me/rmukhamet"
  name = "telegram"
  weight = 7

[[languages.ru.menu.icon]]
  url = "mailto:rmukhametdzhanov@gmail.com"
  name = "envelope-o"
  weight = 8

#[[menu.icon]]
#   # url = "mailto:rmukhametdzhanov@gmail.com"
#    name = "goodreads"
#    weight = 9
   